apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: warehouse
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "http://auth.auth.svc.cluster.local:9000/auth"
    nginx.ingress.kubernetes.io/auth-signin: "http://$host/signin"
    nginx.ingress.kubernetes.io/auth-response-headers: "X-User,X-Email,X-UserId,X-First-Name,X-Last-Name"
spec:
  rules:
    - host: arch.homework
      http:
        paths:
          - path: /warehouse/reserve
            pathType: Prefix
            backend:
              service:
                name: payment
                port:
                  number: 9000
          - path: /warehouse/pay
            pathType: Prefix
            backend:
              service:
                name: payment
                port:
                  number: 9000
          - path: /warehouse/cancel
            pathType: Prefix
            backend:
              service:
                name: payment
                port:
                  number: 9000
          - path: /warehouse/add
            pathType: Prefix
            backend:
              service:
                name: payment
                port:
                  number: 9000
          - path: /warehouse/getProducts
            pathType: Prefix
            backend:
              service:
                name: payment
                port:
                  number: 9000
          - path: /warehouse/getWarehouse
            pathType: Prefix
            backend:
              service:
                name: payment
                port:
                  number: 9000