---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
type: Opaque
data:
  DATABASE_USERNAME: YWRtaW4=
  DATABASE_PASSWORD: cGFzc3dvcmQ=
  DATABASE_NAME: ZGI=
  SPRING_DATASOURCE_URL: {{ printf "jdbc:postgresql://%s:%s/%s" .Values.service.db.host .Values.service.db.sport .Values.service.db.dbname  | b64enc | quote }}
  SPRING_DATASOURCE_USERNAME: YWRtaW4=
  SPRING_DATASOURCE_PASSWORD: cGFzc3dvcmQ=

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.name }}
data:
  SERVER_PORT: "{{ .Values.config.port }}"
  SPRING_JPA_DATABASE: "{{ .Values.config.database }}"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "{{ .Values.config.ddl }}"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "{{ .Values.config.driver }}"
  PAYMENT_URI: http://payment.auth:9000/payment/pay
  NOTIFICATION_URI: http://notification.auth:9000/notification/send
  WAREHOUSE_URI: http://warehouse.auth:9000/warehouse/reserve
  WAREHOUSE_URI_PAY: http://warehouse.auth:9000/warehouse/pay
  WAREHOUSE_URI_CANCEL: http://warehouse.auth:9000/warehouse/cancel
  BILLING_URI: http://billing.auth:9000/billing/sub
  DELIVERY_URI: http://delivery.auth:9000/delivery/reserve
  DELIVERY_URI_CANCEL: http://delivery.auth:9000/delivery/cancel